# Generated by Django 6.0.3 on 2026-04-01 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(upload_to='videos/originals/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hls_480p', models.FileField(blank=True, null=True, upload_to='videos/hls/')),
                ('hls_720p', models.FileField(blank=True, null=True, upload_to='videos/hls/')),
                ('hls_1080p', models.FileField(blank=True, null=True, upload_to='videos/hls/')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.genre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
